version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    platform: linux/x86_64
    ports:
      - '127.0.0.1:6379:6379'
      - '127.0.0.1:8001:8001'
